# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import observer_pb2 as observer__pb2


class ObserverStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.monitor = channel.unary_unary(
        '/Observer/monitor',
        request_serializer=observer__pb2.KeyReq.SerializeToString,
        response_deserializer=observer__pb2.InfoRep.FromString,
        )


class ObserverServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def monitor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ObserverServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'monitor': grpc.unary_unary_rpc_method_handler(
          servicer.monitor,
          request_deserializer=observer__pb2.KeyReq.FromString,
          response_serializer=observer__pb2.InfoRep.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Observer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
