# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: observer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='observer.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0eobserver.proto\"\x15\n\x06KeyReq\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x17\n\x07InfoRep\x12\x0c\n\x04info\x18\x01 \x01(\t2*\n\x08Observer\x12\x1e\n\x07monitor\x12\x07.KeyReq\x1a\x08.InfoRep\"\x00\x62\x06proto3')
)




_KEYREQ = _descriptor.Descriptor(
  name='KeyReq',
  full_name='KeyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='KeyReq.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=39,
)


_INFOREP = _descriptor.Descriptor(
  name='InfoRep',
  full_name='InfoRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='InfoRep.info', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=64,
)

DESCRIPTOR.message_types_by_name['KeyReq'] = _KEYREQ
DESCRIPTOR.message_types_by_name['InfoRep'] = _INFOREP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeyReq = _reflection.GeneratedProtocolMessageType('KeyReq', (_message.Message,), dict(
  DESCRIPTOR = _KEYREQ,
  __module__ = 'observer_pb2'
  # @@protoc_insertion_point(class_scope:KeyReq)
  ))
_sym_db.RegisterMessage(KeyReq)

InfoRep = _reflection.GeneratedProtocolMessageType('InfoRep', (_message.Message,), dict(
  DESCRIPTOR = _INFOREP,
  __module__ = 'observer_pb2'
  # @@protoc_insertion_point(class_scope:InfoRep)
  ))
_sym_db.RegisterMessage(InfoRep)



_OBSERVER = _descriptor.ServiceDescriptor(
  name='Observer',
  full_name='Observer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=66,
  serialized_end=108,
  methods=[
  _descriptor.MethodDescriptor(
    name='monitor',
    full_name='Observer.monitor',
    index=0,
    containing_service=None,
    input_type=_KEYREQ,
    output_type=_INFOREP,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OBSERVER)

DESCRIPTOR.services_by_name['Observer'] = _OBSERVER

# @@protoc_insertion_point(module_scope)
